alias build="pushd ~/cortijo &&  git pull && docker-compose build && docker-compose up -d && popd || popd"
alias  exec="pushd ~/bash && bash docker_exec && popd || popd"
alias  logs="pushd ~/bash && bash docker_logs && popd || popd"
alias  restart="pushd ~/bash && bash docker_restart && popd || popd"
alias  remove="pushd ~/bash && bash docker_remove && popd || popd"
alias  stop="pushd ~/bash && bash docker_stop && popd || popd"
alias  start="pushd ~/bash && bash docker_start && popd || popd"
alias  error="pushd ~/bash && bash docker_error && popd || popd"
